name 'scale_apache'
maintainer 'Southern California Linux Expo'
maintainer_email 'noreply@socallinuxexpo.org'
license 'All rights reserved'
description 'Installs/Configures SCALE webservers'
source_url 'https://github.com/socallinuxexpo/scale-chef'
version '0.1.0'
depends 'fb_apache'
depends 'fb_letsencrypt'
