name 'scale_apache'
maintainer 'Southern California Linux Expo'
maintainer_email 'noreply@socallinuxexpo.org'
license 'All rights reserved'
description 'Installs/Configures SCALE webservers'
source_url 'https://github.com/socallinuxexpo/scale-chef'
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
version '0.1.0'
depends 'fb_apache'
depends 'scale_drupal'
