name 'scale_mailman'
maintainer 'Southern California Linux Expo'
maintainer_email 'noreply@socallinuxexpo.org'
license 'All rights reserved'
description 'Installs/Configures scale_apache'
source_url 'https://github.com/socallinuxexpo/scale-chef'
version '0.1.0'

depends 'scale_apache'
depends 'scale_misc'
