#
# Cookbook Name:: scale_mailman
# Recipe:: postfix

#TODO: POSTFIX should probably move to a generic postfix cookbook

pkgs = %w{
  postfix
  postfix-perl-scripts
}

package pkgs do
  action :upgrade
  notifies :restart, 'service[httpd]'
end

# TODO: this should probably be generated by a provider of some sort
template '/etc/aliases' do
  source 'aliases.erb'
  owner 'root'
  group 'root'
  mode  '0644'
  notifies :run, 'execute[newaliases]', :immediately
end

execute 'newaliases' do
  command 'newaliases'
  creates '/etc/aliases.db'
  action :nothing
  notifies :restart, 'service[postfix]', :immediately
end

service 'postfix' do
  action [:enable, :start]
end
