name 'scale_yum'
maintainer 'Southern California Linux Expo'
maintainer_email 'noreply@socallinuxexpo.org'
license 'All rights reserved'
description 'Installs/Configures yum'
source_url 'https://github.com/socallinuxexpo/scale-chef'
version '0.1.0'
