name 'scale_drupal'
maintainer 'Southern California Linux Expo'
maintainer_email 'noreply@socallinuxexpo.org'
license 'All rights reserved'
description 'Installs/Configures SCAPE Drupal setup'
source_url 'https://github.com/socallinuxexpo/scale-chef'
version '0.1.0'
depends 'scale_misc'
