name: Kitchen tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  kitchen-tests:
    strategy:
      fail-fast: false
      matrix:
        os:
          - centos-stream-9
          - centos-stream-10
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3'
      - name: Install Chef Workstation
        uses: actionshub/chef-install@main
        with:
          project: cinc-workstation
          omnitruckUrl: omnitruck.cinc.sh
      - name: Upgrade kitchen-dokken
        run: gem update kitchen-dokken
        env:
          CHEF_LICENSE: accept-no-persist
      - name: Run test kitchen
        uses: actionshub/test-kitchen@main
        with:
          os: ${{ matrix.os }}
        env:
          CHEF_LICENSE: accept-no-persist
          PATH: /home/runner/.cinc/gem/ruby/3.1.0/bin:/opt/cinc-workstation/bin:${{ env.PATH }}
