name 'scale_web'
maintainer 'SCALE'
maintainer_email 'noreply@socallinuxexpo.org'
license 'Apache-2.0'
description 'Entry point for SCALE webserver'
version '0.1.0'
depends 'fb_apache'
depends 'scale_apache'
depends 'scale_drupal'
